name: Cloud Execute

on:
  workflow_dispatch:
    inputs:
      code:
        description: 'Python code'
        required: true
        type: string

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Restore Library Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/.cache/pip
          key: pip-cache-v1
          restore-keys: pip-cache-v1
      
      - name: Install Dependencies (from cache)
        run: |
          pip install --upgrade pip
          pip install torch torchvision tensorflow transformers
      
      - name: Execute
        run: |
          echo '${{ github.event.inputs.code }}' | base64 -d > code.py
          python code.py
